# Generated by Django 5.2.9 on 2026-04-20 13:16

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('emergency_contact_number', models.CharField(max_length=10)),
                ('residential_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('cycle', 'Cycle'), ('car', 'Car')], max_length=20)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('driving_license_number', models.CharField(max_length=50)),
                ('license_valid_upto', models.DateField()),
                ('pan_card_number', models.CharField(max_length=10)),
                ('aadhaar_image', models.ImageField(blank=True, null=True, upload_to=user.models.rider_upload_path)),
                ('dl_image', models.ImageField(blank=True, null=True, upload_to=user.models.rider_upload_path)),
                ('referral_id', models.CharField(blank=True, max_length=20, null=True)),
                ('is_info_correct', models.BooleanField(default=False)),
                ('is_terms_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
